// STATES ACTIONS
export const LOADING_DATA = "LOADING_DATA"
export const LOADING_AUTH_DATA = "LOADING_AUTH_DATA"
export const CLEAR_LOADING_DATA = "CLEAR_LOADING_DATA"
export const RESET_STATE = "RESET_STATE"
export const RESET_MODAL = "RESET_MODAL"
export const PAGE_NOT_FOUND = "PAGE_NOT_FOUND"

// ERRORS ACTIONS
export const GET_ERRORS = "GET_ERRORS"
export const CLEAR_ERRORS = "CLEAR_ERRORS"

// AUTH ACTIONS
export const AUTH_USER = "AUTH_USER"
export const AUTH_LOGIN = "AUTH_LOGIN"
export const AUTH_LOGOUT = "AUTH_LOGOUT"
export const AUTH_REGISTER = "AUTH_REGISTER"

// OFFER ACTIONS
export const GET_OFFERS = "GET_OFFERS"
export const GET_OFFER = "GET_OFFER"

// GLOBAL ACTIONS
export const MODAL_ON = "MODAL_ON"
export const MODAL_OFF = "MODAL_OFF"
