name: deploy_booker_ui_admin_staging

on:
  push:
    branches:
      - develop

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: booker-staging
  GKE_ZONE: us-central1-c
  DEPLOYMENT_NAME: ui-admin-deploy
  IMAGE: test_booker_ui_admin
  REACT_APP_WEBKIT_URL: ${{ secrets.REACT_APP_WEBKIT_URL_STAGING }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      # CHECK THE DEVELOP INFRA BRANCH AND FETCH SUBMODULES
      - name: Checkout
        uses: actions/checkout@v2
      # SETUP GCLOUD CLI
      - uses: google-github-actions/setup-gcloud@master
        with:
          export_default_credentials: true
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
      # AUTH
      - run: gcloud --quiet auth configure-docker
      # GET GKE CREDENTIALS
      - run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE" --project $PROJECT_ID
      # BUILD IMAGE
      - name: Build
        run: |-
          docker build \
            --tag gcr.io/$PROJECT_ID/$IMAGE \
            --file Dockerfile.production \
            --build-arg REACT_APP_WEBKIT_URL=$REACT_APP_WEBKIT_URL \
            .
      # PUSH IMAGE
      - name: Publish
        run: docker push gcr.io/$PROJECT_ID/$IMAGE
      # DEPLOY TO CLUSTER
      - name: Deploy
        run: kubectl rollout restart deployment $DEPLOYMENT_NAME && kubectl get services -o wide
